### ISSUE TITLE
Ability to use separate textures

### ISSUE THREAD

**Issue by KenneyNL** [AlexSTV/Voxelmetric#11]
Ability to use separate textures instead of a sheet. These textures could possibly be stiched together to a spritesheet on runtime.

**Comment by holmstrom** [comment]
+1 on this - I find it's easy to get tearing issues on the quad sides with a spritesheet if point sampling isn't a good option for textures.

**Comment by AlexSTV** [comment]
I think for performance one sheet is going to be required unless there's a way to get one drawcall per mesh with more than one? I'm not sure what is possible here though. An option would be to stitch them together at run time and add a pit of padding to each tile with the edge pixels repeating.

**Comment by AlexSTV** [comment]
979dfe83c0a6e1a3762036a1b96561edb908ca3a adds this but is in a separate branch for now because of multiple breaking changes.
