### ISSUE TITLE
Connected textures

### ISSUE THREAD

**Issue by KenneyNL** [AlexSTV/Voxelmetric#12]
Allow textures to band together like in the sample below.

![Sample](http://puu.sh/iseGy/e292c524e3.png)

**Comment by AlexSTV** [comment]
Added initial support in 2b3482540b2e388a85619de213b2e9705bf046fa in the branch add_texture_index but I think it still needs work, I just did what was needed to get it working before the end of the weekend.

Connected textures work like this, add the 5 textures to the Connected Textures folder in resources named like this: textureName-c0.png where 0 is the type.
<img width="480" alt="5type" src="https://cloud.githubusercontent.com/assets/5434285/8513830/99c39ba8-2372-11e5-9e36-fba84570a64b.png">

**Comment by KitatusStudios** [comment]
"In test" - One day later - "Closed". What happened? :P

**Comment by AlexSTV** [comment]
I think someone pulled it and got it all running and let me know on twitter or in Gitter. The in test tag doesn't work so well because there's no testing procedure and everyone just pulls and gets stuff running whenever.
