### ISSUE TITLE
Variable to change block size in config

### ISSUE THREAD

**Issue by thegreatpl** [AlexSTV/Voxelmetric#14]
A current time, all blocks except those that have their own mesh are the same fixed size. Being able to change the block size in the config file would allow for smaller blocks, such as games like Cube World have, than the current size.

**Comment by AlexSTV** [comment]
Yeah this would be a good option to have.

**Comment by AlexSTV** [comment]
Ok, I have this just about working, will probably push it tonight :smiley:
