### ISSUE TITLE
Fixed world size

### ISSUE THREAD

**Issue by CorWilson** [AlexSTV/Voxelmetric#17]
How would you deal with having a fixed world size using your chunk system that is built mostly on an infinite world? Would you end up making it where a chunk isn't generated when you reach an edge during the distance check? Also, have you thought of using an object pool rather than creating and destroying chunk game objects like that? On a modern computer, it gives no overhead, but on something like a mobile or less powerful devices, I can see this being quite the slowdown.

**Comment by AlexSTV** [comment]
If you wanted to limit the world size you could probably check that each new chunk is within bounds in LoadChunks. This will leave you with an edge to your world with one unrendered buffer chunk after it. You will have to disable setting blocks in the chunks outside your range to make sure these chunks stay empty by checking the position in the set block function. This will make the edge chunks render their sides facing out and stop players building outwards. I'm not sure this is the best way but it is a way.

Object pooling is a good idea and will likely get implemented in the future.

**Comment by asdfadrian** [comment]
Could you share your code for the proper way as you described above? Im having issues implementing it, only have one border but the other border is still infinite.

This is what I have so far to produce the image below. As for rendering the edges Im not sure how
//in world.cs start
 maptileSize = new Vector2((int)maptileSize.x / Config.Env.ChunkSize, (int)maptileSize.y / Config.Env.ChunkSize);

//in LoadChunks.FindChunksAndLoad()

if (newChunkPos.x < maptileSize.x)
            {
                if (newChunkPos.z < maptileSize.y)
                {
                    //Get the chunk in the defined position
                    Chunk newChunk = world.GetChunk(newChunkPos);

                    //If the chunk already exists and it's already
                    //rendered or in queue to be rendered continue
                    if (newChunk != null && newChunk.loaded)
                        continue;

                    LoadChunkColumn(newChunkPos);
                    return true;
                }
            }

http://i.gyazo.com/1fb1d967e6edebba26ad3aff569ebfaa.png

**Comment by thegreatpl** [comment]
Easiest way to have a limited world I can think of would be generate an infinite wall of indestructible blocks at x, z, and maybe y coords depending on whether you wanted to limit them digging down or upwards. But that would require indestructible blocks to be a thing. Though that is something more to be programmed in the game itself rather than this backend I suppose. 

For example: 
if (World.GetBlock(blockPos).type != Block.IndestructibleBlock.type)
{
        SetBlock(blockpos, block); 
}

That way you would limit the players to an area. You'd then add to, or replace, the terrain generation and have it set blocks all blocks on row minX, minZ, maxX, and maxZ. That would box them into a smaller area at the least. Also add the same for min Y and max Y if you want, but would be more interesting to have them able to dig infinitely down or up I suppose. 

That is, if Y still remains the up or down. I haven't actually checked.

**Comment by holmstrom** [comment]
The easiest solution (as in least coding/changes to the framework needed) to this is IMO to simply constrain the player movement to certain positions in the world. Since the player moving around with the LoadChunks script is what's making the world generate new terrain, just make it so the player can't move past a certain point. This can be done in multiple easy ways, e.g. LimitX, LimitY, LimitZ values on the player script, a bounding box that won't allow the player to leave etc.

**Comment by asdfadrian** [comment]
That would be a perfect solution for the time being holmstrom which is what Im using but the problem with that is you dont see the edge of the map with the sides being rendered as I hoped

**Comment by holmstrom** [comment]
@asdfadrian I'm not sure what you mean by "the edge of the map". Do you want blocks to wall of the map, or do you want to see the actual edge of the map? If it's the former, I'd say it's better to use the block texture to wall of the map on top of a quad. If it's the latter (i.e. you want the player to be able to walk up to the edge without more chunks being generated) I think the easiest solution is to set a trigger on the "border lands" that will stop the LoadChunk script from running until you leave those areas. I.e. if you have a chunk load radius of 10 blocks, you set up trigger volumes around the edges of the world that will stop new chunks from generating when you are 10 blocks from the edge of the world as you see it. Makes sense?

**Comment by asdfadrian** [comment]
Well Im planning to use this as a terrain engine. The player is actually nonexistent and rather a camera looking down in an RTS manner is where Im trying to with. Im not really following the latter approach but Im just going off of what Alex mentioned above as it seems more logical and relatable to look into an already existing script to modify. 

Sorry with the confusion!

**Comment by asdfadrian** [comment]
Okay I forgot to consider the fact that the chunks generate radially to the players position which is even better and easier therefor I just updated my conditions in FindChunksAndLoad as such:

            if (-world.maptileSize.x <= newChunkPos.x && newChunkPos.x <= world.maptileSize.x)
            {
                if (-newChunkPos.z <= world.maptileSize.y && newChunkPos.z <= world.maptileSize.y)
                {

http://i.gyazo.com/ba1b780d77369a22f9172a73082b9685.png

However, I notice that as the player position moves towards the edge, theres a big drop in framerates. I think it has something to do with it trying to call additional chunks regardless of the boundaries being set? Maybe Id have to look more into the SetBlock.

**Comment by thegreatpl** [comment]
Problem to consider with the above: if you walk over the edge with gravity, then you'll fall forever. Terrain is infinite in all three directions I believe. 

In comparison, holmstrom suggested you constrain the player from leaving the map. Ie, whatever script you use to interact with the player has something like: 

if (playerPos.x < -world.worldConstraints.x)
{
playPos.x = -world.worldConstraints.x;
}
else if (playerPos.x > world.worldConstraints.x)
{
playerPos.x = world.worldConstraints.x; 
}

if (playerPos.z < -world.worldConstraints.z)
{
playPos.z = -world.worldConstraints.z;
}
else if (playerPos.z > world.worldConstraints.z)
{
playerPos.z = world.worldConstraints.z; 
}

This means you don't have to touch any of voxelmetric's code to limit them in. The disadvantage is the so called invisible wall which this will cause.

**Comment by CorWilson** [comment]
In my own engine, I did what thegreatpl did: just add a movement constraint in your character movement script. The invisible wall is a fine alternative and you can have it where no blocks at the edge of each axis (+x, -x, +z, -z, +y, -y) is unable to be mined. And with a notification, you can tell your player this part of the world is off limits. It loses a little immersiveness, but a fine price to pay so the player won't think the game has a bug.

**Comment by asdfadrian** [comment]
@thegreatpl or you can not walk over by limiting the boundaries in the player movement itself then limit the terrain generation as Im using somewhat simulate invisible walls for now
