### ISSUE TITLE
A way to load custom meshes at run time

### ISSUE THREAD

**Issue by AlexSTV** [AlexSTV/Voxelmetric#26]
Currently custom mesh blocks can only be created in the editor, it uses AssetDatabase.LoadAssetAtPath which cannot be called outside of the editor. It would be nice make it possible to get the mesh at runtime so that the models could be edited or changed outside of unity. I am not sure though how to get a file from a folder and fetch its data at runtime though.

**Comment by KenneyNL** [comment]
This would indeed be a great feature, even more so when you think of mods for Voxelmetric powered games.

**Comment by asdfadrian** [comment]
Good point KenneyNL, didnt think of that. This would be awesome!

**Comment by holmstrom** [comment]
Shouldn't Resources.Load work?

http://docs.unity3d.com/ScriptReference/Resources.Load.html

You do need to keep the files in a specific folder, but it seems like you can load them from disk at least.

**Comment by HeadClot** [comment]
I would honestly like this feature :)

**Comment by AlexSTV** [comment]
979dfe83c0a6e1a3762036a1b96561edb908ca3a adds this but is in another branch for now. I made it load all the meshes in resources/meshes automatically as blocks using their names as the block name. Unfortunately it gets the actual mesh's name, not the file name.
