### ISSUE TITLE
random terrain generation

### ISSUE THREAD

**Issue by macwad1** [AlexSTV/Voxelmetric#28]
i am decently new to coding and was wondering if there was any way to have this do random terrain generation, because at the moment the terrain that appears is always exactly the same

**Comment by AlexSTV** [comment]
Adding to this it would be nice

**Comment by AlexSTV** [comment]
You can make the terrain different each time by adding numbers to the y variable in GetNoise() in the TerrainGen class, for example at the start of that function add y+=-32853;

This should eventually be built as a feature. TerrainGen could be modified to take a seed in its constructor, convert it to an int and multiply it by some large number (so we don't get very similar terrain for similar seeds) and then add that to y in get noise. Then World class could pass the world name as a seed and each unique world name would get different terrain.

**Comment by macwad1** [comment]
ok, i will try that, thank you very much

**Comment by AlexSTV** [comment]
@macwad1 Hey, I implemented a seed system last night in the add_texture_index branch after thinking about this for a while :smile: It generates a permutation array for the simplex noise using the world name as the seed. I'm on (Gitter)[https://gitter.im/AlexSTV/Voxelmetric] if you need any help.

**Comment by macwad1** [comment]
thank you very much for adding this feature, it should help out with what i am trying to code

**Comment by macwad1** [comment]
i must say that i am a huge fan of yours, i did your entire tutorial on your website and really loved it, it helped me learn about code and also get into unity
