### ISSUE TITLE
Add a voxel file importer for blocks

### ISSUE THREAD

**Issue by Penple03** [AlexSTV/Voxelmetric#38]
Allow for .vox or .qb blocks

**Comment by Dalez** [comment]
You can export this to a .obj and import it into unity. I don't think Unity supports .vox (as far as I am aware). 

Hopefully with an update that Alex is pushing soon, you don't need to use another program to change the submeshes name, so you should just be able to use a .obj file.

**Comment by Penple03** [comment]
I know but a built in importer would improve productivity, and think about it, it's a voxel framework, we have everything we need, it just has to be smaller.

**Comment by HeadClot** [comment]
I plan on getting [Qubicle 2](http://www.minddesk.com/) at the end of the month so this would be appreciated :)

**Comment by Ecu** [comment]
Qubicle is a great tool.  The *.qb format is documented [here](http://minddesk.com/wiki/index.php?title=Qubicle_Constructor_1:Data_Exchange_With_Qubicle_Binary).

However, I can see some issues.  Simply, the voxel files would require optimized mesh conversion each load (or caching it, which means exporting some form of mesh optimized mesh file).  If you're caching an optimized mesh, why not just import an object file in the first place?

**Comment by AlexSTV** [comment]
Like @Ecu said, the people that make voxel editor programs will be optimizing mesh export for their stuff much better than we can hope to pull off in Voxelmetric so I don't see a good reason too build a voxel file to mesh conversion.

**Comment by Ecu** [comment]
I will say, it would be interesting to be able to do a Voxelmetric world -> object file export though (preferably via code, so it could be done in-game).  This could be very useful in multiple ways.

Some examples:
* Users exporting maps to render them in another 3D program.
* Using a world as a in-game model editor to create content for the game, in the game.
* Using a world as a block in another world (say you want snow globes that show another world).

**Comment by AlexSTV** [comment]
@Ecu Definitely, Voxelmetric world data converting to and from open voxel formats would be a useful feature.

**Comment by barraudf** [comment]
For those interested in importing MagicaVoxel (.vox) files, you can check this : https://github.com/darkfall/MagicaVoxelUnity

**Comment by HeadClot** [comment]
Thank you for the heads up @barraudf
