### ISSUE TITLE
Solid color blocks

### ISSUE THREAD

**Issue by Penple03** [AlexSTV/Voxelmetric#41]
I feel as this is a very simple question, but I have been trying for ages. Is there any way I can use Voxelmetric to have solid color blocks. I have placed a checkbox and a color input in my Definition script, but I can't for the life of me figure out how to make my block a solid color. I am trying to avoid a texture of any kind, because I want the color different depending on the location. In the long run I want to have the ability to select a color, and it will be slightly different depending on the location / biome.

I am not asking anybody to make this for me, I would just like pointers in the right direction.

**Comment by barraudf** [comment]
To use color without textures, you need 2 things :
- set the model color,, using [Mesh.colors](http://docs.unity3d.com/ScriptReference/Mesh-colors.html) (or Mesh.colors32)
- use a shader that take verices' color into account

Also, you don't need to set UVs anymore. That's what I'm trying to do in my own engine, I don't know if this can easily be done with voxelmetric (I guess it is)

**Comment by Penple03** [comment]
I can't believe I didn't think of that. I was trying to generate a 1x1 texture and apply it at runtime. I have a vertex color shader but how would you go about finding what vertices I need to modify?

**Comment by barraudf** [comment]
Basically, you have your vetex list (say `List<Vector3> vertices;`). Simply add a `List<Color32> colors;`.

Every time you add a vertex to the list, add its color too!

Then when you populate the Mesh data, add `Mesh.colors32 = colors.ToArray();`

**Comment by Penple03** [comment]
But aren't the vertices shared? Won't the color bleed to other blocks next to them?

**Comment by barraudf** [comment]
I don't think they are shared (from files in Voxelmetric/Assets/Voxelmetric/Code/Blocks/Builders/)

**Comment by Penple03** [comment]
After a very long fight with Voxelmetric mostly consisting of trying to make my own vertex color system and halfway through realising that Voxelmetric already had one so I had to integrate mine with it's. I was able to set it all up.
![](http://i.imgur.com/qgQysEz.png)
It's still not much, but a first step in what I'm creating
