### ISSUE TITLE
Issue with Documentation on AlexStv Website

### ISSUE THREAD

**Issue by kinggrinyov** [AlexSTV/Voxelmetric#44]
The "Interacting with Voxelmetric" section of the docs is missing. when i click on the link/button given, it leads to an 'Error 404". I'd really like to know what info i'm missing out on! its like the most important part :P
![untitled](https://cloud.githubusercontent.com/assets/13958688/9460875/5091f08a-4b4d-11e5-890c-7b157f7e35f4.png)

**Comment by HeadClot** [comment]
@kinggrinyov - I am getting this as well. 

Link to the page below

http://alexstv.com/index.php/interacting-with-voxelmetric

**Comment by AlexSTV** [comment]
Sorry about that, misnamed the page. It should be working now.
