### ISSUE TITLE
Chunks stop adding and deleting themselves

### ISSUE THREAD

**Issue by Neomex000** [AlexSTV/Voxelmetric#57]
Hey there,
When I walk for few seconds I'm reaching end of map. It looks like the chunks don't want to generate futher for some reason, but also old ones aren't deleted.

I really wanted to use this for my project, it has everything except water and biomes :)

Please fix.

**Comment by AlexSTV** [comment]
I'll take a look but I think mine is working fine. To help me replicate it, what branch are you on and are you using the LoadChunks script? If you're using the LoadChunks script can you make sure that it is on the object you want to load chunks around?

**Comment by Neomex000** [comment]
I didn't realise I had to have LoadChunks script on a camera, now its working!

**Comment by AlexSTV** [comment]
Fantastic!
