### ISSUE TITLE
Mesh blocks in addition to voxels

### ISSUE THREAD

**Issue by KenneyNL** [AlexSTV/Voxelmetric#8]
Allow using custom meshes in addition to normal voxels. These meshes can be used to create plants and detailed blocks like fences.

**Comment by AlexSTV** [comment]
Made a big change to let blocks be defined in the scene in 0174236a4aeefcaee1d95a6a855325b2e0b92577. So now blocks types are defined by adding scripts from the code/blocks/block definitions/ folder onto the World game object.

I've added a block definition for a block with a custom model called CustomMesh.  Then in this script you can define a block name and a the name of a 3d model placed in assets/Voxelmetric/BlockMeshes/. Clicking the checkmark next to build will save the mesh's vertexes and UV coordinates to use as a block.]

I'll add an example to the default scene once I create a model to use for it.

**Comment by AlexSTV** [comment]
Now there's an example in the default scene (with a beautifully modelled pyramid thing I made myself!) and documentation in the wiki: https://github.com/AlexSTV/Voxelmetric/wiki/Defining-blocks

**Comment by AlexSTV** [comment]
Closing this since the basic functionality is implemented, a new issue can be used if bugs crop up and additional enhancements will come later.
